apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ur2ytu3sx-go 
  janus-idp.io/tekton: ur2ytu3sx-go
  backstage.io/kubernetes-id: ur2ytu3sx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ur2ytu3sx-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml