apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ur2ytu3sx-go
  janus-idp.io/tekton: ur2ytu3sx-go
  backstage.io/kubernetes-id: ur2ytu3sx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ur2ytu3sx-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
