apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ur2ytu3sx-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:04ef6049285eb95988ca711565d0aee5fd476859@sha256:5bc351a5f93b3b7a56e976daf269870587b5e85ae9850bcbfe90040e7cb6b8f7
          name: container-image
